const responseMessage = {
    ADD_DATA_SUCCESS : '정보 추가 성공',
    ADD_DATA_FAIL : '정보 추가 실패',
    READ_DATA_SUCCESS : 'DATA 읽기 성공',
    READ_DATA_FAIL : 'DATA 읽기 실패',
    HAVE_SAME_TITLE : '제목이 중복됨',
    ID_OR_PASSWORD_INCORRECT : 'ID나 비밀번호가 일치하지 않음',
    DATA_CHANGE_SUCCESS : 'DATA 수정 성공',
    DATA_CHANGE_FAIL : 'DATA 수정 실패',
    DATA_DELETE_SUCCESS : 'DATA 삭제 성공',
    NO_USER_IN_DATA : '해당하는 유저가 없거나, 유저의 게시글이 없음',
    NULL_VALUE : '입력되지 않은 값이 존재함',
    DB_FAILED : 'DB 커넥션 에러',
    SIGNIN_SUCCESS : '로그인 성공',
    NO_DATA : '게시글이 없음',
    ALREADY_USER : 'ID가 중복됨',
    SIGNUP_SUCCESS : '회원가입 성공',
    /* ---------------- */
    NO_WEBTOON : '해당하는 웹툰이 없음',
    NO_EPISODE : '해당하는 에피소드가 없음',
    READ_EPISODE_LIST_SUCCESS : '에피소드 목록 읽어오기 성공',
    READ_EPISODE_SUCCESS : '에피소드 불러오기 성공',
    ADD_EPISODE_FAIL : '에피소드 추가 실패',
    ADD_EPISODE_SUCCESS : '에피소드 추가 성공',
    UPDATE_EPISODE_FAIL : '에피소드 수정 실패',
    UPDATE_EPISODE_SUCCESS : '에피소드 수정 성공',
    DELETE_EPISODE_SUCCESS : '에피소드 삭제 성공',
    READ_EPISODE_FAIL : '에피소드 불러오기 실패',

    ADD_COMMENT_FAIL : '코멘트 추가 실패',
    ADD_COMMENT_SUCCESS : '코멘트 추가 성공',
    UPDATE_COMMENT_FAIL : '코멘트 수정 실패',
    UPDATE_COMMENT_SUCCESS : '코멘트 수정 성공',
    DELETE_COMMENT_FAIL : '코멘트 삭제 실패',
    DELETE_COMMENT_SUCCESS : '코멘트 삭제 성공',
    NO_UPDATE_AUTHORITY : '수정 권한이 없는 유저',
    NO_COMMENTS : '코멘트가 없음',
    READ_COMMENTS_SUCCESS : '코멘트 불러오기 성공',
    SIGNUP_FAIL : '회원가입 실패',

    /* ---------------- */
    READ_WEBTOON_LIST_SUCCESS : '웹툰 리스트 읽어오기 성공',
    ADD_WEBTOON_FAIL : '웹툰 추가 실패',
    ADD_WEBTOON_SUCCESS : '웹툰 추가 성공',
    UPDATE_WEBTOON_FAIL : '웹툰 수정 실패',
    UPDATE_WEBTOON_SUCCESS : '웹툰 수정 성공',
    DELETE_WEBTOON_SUCCESS : '웹툰 삭제 성공',
    DELETE_WEBTOON_FAIL : '웹툰 삭제 실패',
    NO_CATEGORY : '해당하는 카테고리가 없음.',
    READ_WEBTOON_LIST_FAIL : '웹툰 리스트 읽어오기 실패',
    LIKE_SUCCESS : '좋아요 성공',
    LIKE_FAIL : '좋아요 실패',
    GET_LIKE_SUCCESS : '좋아요 가져오기 성공',
    GET_LIKE_FAIL : '좋아요 가져오기 실패'

}

module.exports = responseMessage;